- name: Check if Docker is installed
  ansible.builtin.command: which docker
  register: docker_installed
  ignore_errors: true
  changed_when: false

- name: Create keyrings directory if needed
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true
  when: docker_installed.rc != 0

- name: Add Docker GPG key if needed
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  become: true
  when: docker_installed.rc != 0

- name: Add Docker repo
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
  become: true
  when: docker_installed.rc != 0

- name: Install Docker and Docker Compose (plugin v2)
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true
  become: true
  when: docker_installed.rc != 0

- name: Ensure Docker service is enabled and started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
